[package]
name = "gen-waveform"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cpal = "0.15"
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
ratatui = "0.28"
crossterm = "0.28"

[profile.release]
lto = true
opt-level = 3
